#!/bin/sh
# Aliases

# General
alias ls='ls -hNv --color=auto --group-directories-first'
alias ll='ls -l --time-style=long-iso'
alias lla='ll -A'

alias grep='grep --color=auto'
alias diff='diff --color=auto'

alias v='$EDITOR'
alias vv='v .'
alias vvv='f="$(fzf)"; [ -n "$f" ] && $EDITOR "$f"'
alias gg='f="$(find "$HOME" -type d | fzf)"; [ -n "$f" ] && cd "$f"'


alias alert='notify-send --urgency=low "$([ $? = 0 ] && echo "Suksess" || echo "Feil")" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias groff='groff -Kutf8 -P-pa4 -dpaper=a4'
alias d='devour'

alias tm='tmux-sessionizer'

# Git
alias g='git status'
alias gd='git diff'
alias gp='git pull --rebase'
alias gpm='branch=$(git rev-parse --abbrev-ref HEAD) && git switch master && gp && git switch $branch && git fetch'
alias gbl='git branch | fzf | xargs git switch && git fetch'
alias gb="git branch -r | fzf | sed -e 's/^\s*origin\///' | xargs git switch && git fetch"
alias gba='git branch -a | fzf | xargs git switch && git fetch'
alias gl='git log --color --graph | less -R'
alias glr='git log --color --graph --remotes | less -R'
alias glm='git log --color --pretty=format:'"'"'%C(red)%h%C(reset) %C(green)%ad%C(reset) %s %C(bold blue)<%an>%C(reset)%C(yellow)%d%C(reset)'"'"' --graph --date=short | less -R'

